/**
 * @file Layout template
 * @description Generated by agent. Wrap children and define global layout.
 */

import React, { ReactNode } from 'react';

/**
 * Layout for ComponentName
 * @param {{children: ReactNode}} props
 * @returns {JSX.Element}
 */
export default function ComponentNameLayout({ children }: { children: ReactNode }): JSX.Element {
  return (
    <div className="min-h-screen bg-background text-foreground">
      <header>ComponentName Layout Header</header>
      <main>{children}</main>
    </div>
  );
}
