/**
 * @file Middleware template
 * @description Generated by agent. Add middleware logic and conditions.
 */

import { NextResponse } from 'next/server';
import type { NextRequest } from 'next/server';

/**
 * Middleware for ComponentName
 * @param {NextRequest} request
 * @returns {NextResponse}
 */
export function middleware(request: NextRequest): NextResponse {
  // Add logic, for example access control
  return NextResponse.next();
}
